"""Creating migration

Revision ID: 43d05a1bac7f
Revises: 5c80b71144cc
Create Date: 2025-10-05 10:07:05.357920

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "43d05a1bac7f"
down_revision = "5c80b71144cc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    message_state_enum = postgresql.ENUM("FAILED", "FULFILLED", "PENDING", name="messagestate")
    message_state_enum.create(op.get_bind(), checkfirst=True)

    # Alter existing columns
    op.alter_column(
        "chat_session", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "chat_session", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.drop_index(op.f("ix_chat_session_id"), table_name="chat_session")

    # Add new enum column
    op.add_column(
        "message",
        sa.Column(
            "state",
            message_state_enum,
            nullable=True,
        ),
    )

    op.alter_column("message", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("message", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.drop_index(op.f("ix_message_id"), table_name="message")

    op.alter_column("user", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("user", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.drop_index(op.f("ix_user_id"), table_name="user")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "state")

    # Drop ENUM type
    message_state_enum = postgresql.ENUM("FAILED", "FULFILLED", "PENDING", name="messagestate")
    message_state_enum.drop(op.get_bind(), checkfirst=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.alter_column("user", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("user", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.create_index(op.f("ix_message_id"), "message", ["id"], unique=False)
    op.alter_column("message", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("message", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.drop_column("message", "state")
    op.create_index(op.f("ix_chat_session_id"), "chat_session", ["id"], unique=False)
    op.alter_column(
        "chat_session", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "chat_session", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###
